import 'intl';
export const localization=require('@assets/data/bebbo/localization').default;
export const sponsers=require('@assets/data/bebbo/sponsers').default;
import bebboLogoShape1 from '@assets/svg/bebbo/bebbo_logo_shape.svg';
export const bebboLogoShape=bebboLogoShape1;
import bebboLogoShapeNew1 from '@assets/svg/bebbo/bebbo_logo_shape1.svg';
export const bebboLogoShapeNew=bebboLogoShapeNew1;
import adviceFeatureLogo from '@assets/svg/advice_feature_logo.svg';
export const adviceLogo=adviceFeatureLogo;
import toolsFeatureLogo from '@assets/svg/tools_features_logo.svg';
export const toolsLogo=toolsFeatureLogo;
import activityFeatureLogo from '@assets/svg/activity_feature_logo.svg';
export const activityLogo=activityFeatureLogo;
import imgLogoChatbotNew1 from '@assets/svg/bebbo/img-logo-chatbot-new.svg';
export const imgLogoChatbotNew=imgLogoChatbotNew1;
export const AVAILABLE_LANGUAGES =require('../localization/Available_lang_bebbo').default;
export const taxonomydata =require('@offlinedata/bebbo/taxonomies').taxonomydata;
export const ActivitiesData =require('@offlinedata/bebbo/ActivitiesData').ActivitiesData;
export const articledata = require('@offlinedata/bebbo/article').articledata;
export const basicPagesData =require('@offlinedata/bebbo/basicPages').basicPagesData;
export const ChildDevelopmentData= require('@offlinedata/bebbo/ChildDevelopmentData').ChildDevelopmentData;
export const FaqsData = require('@offlinedata/bebbo/FaqsData').FaqsData ;
export const healthCheckupsData =require('@offlinedata/bebbo/healthCheckupsData').healthCheckupsData;
export const dailyHomeNotificationdata =require('@offlinedata/bebbo/dailyHomeNotification').dailyHomeNotificationdata;
export const MileStonesData =require('@offlinedata/bebbo/MileStonesData').MileStonesData;
export const standardDevData =require('@offlinedata/bebbo/standardDevData').standardDevData;
export const SurveyData =require('@offlinedata/bebbo/SurveyData').SurveyData;
export const vaccineData =require('@offlinedata/bebbo/vaccineData').vaccineData;
export const VideoArticleData =require('@offlinedata/bebbo/VideoArticleData').VideoArticleData;
import northMacedinaPartnerLogo from '@assets/appOfflineImages/northmacedonia/partner/1.png';
export const nmPartnerLogo=northMacedinaPartnerLogo;
import northMacedinaSponserLogo from '@assets/appOfflineImages/northmacedonia/sponser/2.png';
export const nmSponserLogo=northMacedinaSponserLogo;
import albeniaPartnerLogo from '@assets/appOfflineImages/albenia/partner/IPH.png';
export const albeniaPartnerLogo1=albeniaPartnerLogo;
import belarusPartnerLogo from '@assets/appOfflineImages/belarus/partner/Минобр.png';
export const blParterLogo=belarusPartnerLogo;
import belarusSponserLogo from '@assets/appOfflineImages/belarus/sponser/Минздрав.png';
export const blSponserLogo=belarusSponserLogo;
import krygistanPartnerLogo from '@assets/appOfflineImages/krygystan/partner/LogoMoESKGWhiteSide.png';
export const kgPartnerLogo=krygistanPartnerLogo;
import menterNegroPartnerLogo from '@assets/appOfflineImages/menternegro/partner/MoHMontenegroLogo_0.png';
export const mnParterLogo=menterNegroPartnerLogo;
import menterNegroSponserLogo from '@assets/appOfflineImages/menternegro/sponser/EUlogozaaplikaciju.png';
export const mnSponserLogo=menterNegroSponserLogo;
import serbiaPartnerLogo from '@assets/appOfflineImages/serbia/partner/GZZJZNtionalPartner1000WideWith.png';
export const sbPartnerLogo=serbiaPartnerLogo;
import serbiaSponserLogo from '@assets/appOfflineImages/serbia/sponser/nordeusFondacijaLogo1000Wide.png';
export const sbSponserLogo=serbiaSponserLogo;
import slovakiaPartnerLogo from '@assets/appOfflineImages/slovakia/partner/PEDIATRIlogarium01av.png'
export const skParterLogo=slovakiaPartnerLogo;
import tejikistanPartnerLogo from '@assets/appOfflineImages/tejikistan/partner/MOH_Tajikistan_Logo_TAJ.png'
export const tjkParterLogo=tejikistanPartnerLogo;
import uzbekistanPartnerLogo from '@assets/appOfflineImages/uzbekistan/partner/newMinistry161121Test2.png';
export const uzPartnerLogo=uzbekistanPartnerLogo;
import uzbekistanSponserLogo from '@assets/appOfflineImages/uzbekistan/sponser/Untitled.png';
export const uzSponserLogo=uzbekistanSponserLogo;