import 'intl';
export const localization=require('@assets/data/bebbo/localization').default;
import bebboLogoShape1 from '@assets/svg/bebbo/bebbo_logo_shape.svg';
export const bebboLogoShape=bebboLogoShape1;
import imgLogoChatbotNew1 from '@assets/svg/bebbo/img-logo-chatbot-new.svg';
export const imgLogoChatbotNew=imgLogoChatbotNew1;
import menubebboLogo from '@assets/svg/bebbo/bebbomenulogo.svg';
export const menubebboLogoNew=menubebboLogo;
export const AVAILABLE_LANGUAGES =require('../localization/Available_lang_bebbo').default;
export const taxonomydata =require('@offlinedata/bebbo/taxonomies').taxonomydata;
export const ActivitiesData =require('@offlinedata/bebbo/ActivitiesData').ActivitiesData;
export const articledata = require('@offlinedata/bebbo/article').articledata;
export const basicPagesData =require('@offlinedata/bebbo/basicPages').basicPagesData;
export const ChildDevelopmentData= require('@offlinedata/bebbo/ChildDevelopmentData').ChildDevelopmentData;
export const FaqsData = require('@offlinedata/bebbo/FaqsData').FaqsData ;
export const healthCheckupsData =require('@offlinedata/bebbo/healthCheckupsData').healthCheckupsData;
export const dailyHomeNotificationdata =require('@offlinedata/bebbo/dailyHomeNotification').dailyHomeNotificationdata;
export const MileStonesData =require('@offlinedata/bebbo/MileStonesData').MileStonesData;
export const standardDevData =require('@offlinedata/bebbo/standardDevData').standardDevData;
export const SurveyData =require('@offlinedata/bebbo/SurveyData').SurveyData;
export const vaccineData =require('@offlinedata/bebbo/vaccineData').vaccineData;
export const VideoArticleData =require('@offlinedata/bebbo/VideoArticleData').VideoArticleData;
