import 'intl';
export const localization=require('@assets/data/bangla/localization').default;
export const sponsors=require('@assets/data/bangla/sponsors').default;
import bebboLogoShape1 from '@assets/svg/bangla/bebbo_logo_shape.svg';
export const bebboLogoShape=bebboLogoShape1;
import bebboLogoShapeNew1 from '@assets/svg/bangla/bebbo_logo_shape1.svg';
export const bebboLogoShapeNew=bebboLogoShapeNew1;
import adviceFeatureLogo from '@assets/svg/advice_feature_logo.svg';
export const adviceLogo=adviceFeatureLogo;
import toolsFeatureLogo from '@assets/svg/tools_features_logo.svg';
export const toolsLogo=toolsFeatureLogo;
import activityFeatureLogo from '@assets/svg/activity_feature_logo.svg';
export const activityLogo=activityFeatureLogo;
import imgLogoChatbotNew1 from '@assets/svg/bangla/img-logo-chatbot-new.svg';
import cameraProfile from '@assets/svg/camera_profile.svg';
export const cameraProfileImage=cameraProfile;
export const imgLogoChatbotNew=imgLogoChatbotNew1;
export const AVAILABLE_LANGUAGES =require('../localization/Available_lang_bangla').default;
export const taxonomydata =require('@offlinedata/bangla/taxonomies').taxonomydata;

export const countryData =require('@offlinedata/bangla/countryData').countryData;
export const ActivitiesData =require('@offlinedata/bangla/ActivitiesData').ActivitiesData;
export const articledata = require('@offlinedata/bangla/article').articledata;
export const basicPagesData =require('@offlinedata/bangla/basicPages').basicPagesData;
export const ChildDevelopmentData= require('@offlinedata/bangla/ChildDevelopmentData').ChildDevelopmentData;
export const FaqsData = require('@offlinedata/bangla/FaqsData').FaqsData ;
export const healthCheckupsData =require('@offlinedata/bangla/healthCheckupsData').healthCheckupsData;
export const dailyHomeNotificationdata =require('@offlinedata/bangla/dailyHomeNotification').dailyHomeNotificationdata;
export const MileStonesData =require('@offlinedata/bangla/MileStonesData').MileStonesData;
export const standardDevData =require('@offlinedata/bangla/standardDevData').standardDevData;
export const SurveyData =require('@offlinedata/bangla/SurveyData').SurveyData;
export const vaccineData =require('@offlinedata/bangla/vaccineData').vaccineData;
export const VideoArticleData =require('@offlinedata/bangla/VideoArticleData').VideoArticleData;
import banglaPartnerLogo from '@assets/appOfflineImages/bangla/partner/MoH_bangladesh.png';
export const bnPartnerLogo=banglaPartnerLogo;
import banglaSponserLogo from '@assets/appOfflineImages/bangla/sponser/BSA_logo.png';
export const bnSponserLogo=banglaSponserLogo;