require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
# use_frameworks!

# # Convert all permission pods into static libraries
# pre_install do |installer|
#   Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}

#   installer.pod_targets.each do |pod|
#     if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-') || pod.name.eql?('RNScreens')
#       def pod.build_type;
#         # Uncomment one line depending on your CocoaPods version
#         Pod::BuildType.static_library # >= 1.9
#         # Pod::Target::BuildType.static_library # < 1.9
#       end
#     end
#   end
# end
target 'ParentBuddyApp' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'



  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'ParentBuddyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
   use_flipper!
   post_install do |installer|
     flipper_post_install(installer)
   end
 end

target 'ParentBuddyApp-tvOS' do
  # Pods for ParentBuddyApp-tvOS

  target 'ParentBuddyApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
