# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-permissions/scripts/setup'

# Firebase (modular header support)
# pod 'Firebase', :modular_headers => true  
# pod 'FirebaseCore', :modular_headers => true
# pod 'FirebaseCoreExtension', :modular_headers => true
# pod 'FirebaseSessions', :modular_headers => true
# pod 'FirebaseInstallations', :modular_headers => true
# pod 'GoogleDataTransport', :modular_headers => true
# pod 'nanopb', :modular_headers => true
# pod 'GoogleUtilities', :modular_headers => true

# Permissions
setup_permissions([
  'AppTrackingTransparency',
  'Camera',
  'PhotoLibrary',
  'PhotoLibraryAddOnly',
])

# Optional shared pods
def shared_pods
  # pod 'react-native-lottie-splash-screen', :path => '../node_modules/react-native-lottie-splash-screen'
  # pod 'lottie-ios', '4.5.0'
  # pod '@attarchi/react-native-lottie-splash-screen', :path => '../node_modules/@attarchi/react-native-lottie-splash-screen'
  pod 'lottie-ios'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
end

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
else
  use_frameworks! :linkage => :static
end

target 'ParentBuddyApp' do
  config = use_native_modules!

  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  shared_pods

  # Unit test target
  target 'ParentBuddyAppTests' do
    inherit! :complete
  end

  # Multibranding app targets
  %w[
    ParentBuddyAppXk
    ParentBuddyAppDev
    ParentBuddyAppXkDev
    ParentBuddyAppBangla
    ParentBuddyAppBanglaDev
    MerhabaBebek
    Wawamor
    REMOVED_FACEBOOK_APP_ID1
    REMOVED_FACEBOOK_APP_ID1Pacific
  ].each do |variant_target|
    target variant_target do
      shared_pods
    end
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Xcode 26 workaround: patch fmt to disable consteval
  fmt_base = File.join(installer.sandbox.root, 'fmt', 'include', 'fmt', 'base.h')
  if File.exist?(fmt_base)
    content = File.read(fmt_base)
    unless content.include?('Xcode 26 workaround')
      patched = content.gsub(
        /^(#elif defined\(__cpp_consteval\)\n#  define FMT_USE_CONSTEVAL) 1/,
        "// Xcode 26 workaround: disable consteval\n\\1 0"
      )
      if patched != content
        File.chmod(0644, fmt_base)
        File.write(fmt_base, patched)
      end
    end
    end
  end
end
