export const ONBOARDING_CHILD_COUNT = 'no_of_childsetup_onboarding'; //child_count
export const GROWTH_MEASUREMENT_ADDED = 'child_measurement_entered';
export const VACCINE_ADDED = 'child_vaccine_entered';
export const ADVICE_CATEGORY_SELECTED = 'advise_category_selected';
export const GAME_CATEGORY_SELECTED = 'game_category_selected'; //{game_category_id: 'P12453',}
export const ADVICE_DETAILS_OPENED = 'advise_details_opened'; //,{advise_id: 'P12453',advice_catergory_id}
export const GAME_DETAILS_OPENED = 'game_details_opened'; //{game_id: 'P12453',game_category_id}
export const CHILD_MILESTONE_TRACKED = 'child_milestone_tracked'; //,{age_id: 'P12453'}
export const VACCINE_REMINDER_SET = 'child_vaccine_reminder_set';
export const HEALTH_CHECKUP_ENTERED = 'child_health_checkup_entered'; //,{age_id: 'P12453"}
export const GAME_AGEGROUP_SELECTED = 'game_age_group_selected'; //,{age_id: 'P12453"}
export const ADVICE_AGEGROUP_SELECTED = 'advice_age_group_selected'; //,{age_id: 'P12453"}
export const CHILD_DEVELOPMENT_AGEGROUP_SELECTED =
  'child_development_age_group_selected'; //,{age_id: 'P12453"}
export const HEALTH_CHECKUP_REMINDER_SET = 'child_health_checkup_reminder_set';
export const EXPECTED_CHILD_ENTERED = 'expected_child_entered';
export const FEEDBACK_SUBMIT = 'feedback_submitted';
export const SURVEY_SUBMIT = 'survey_submitted';
export const APP_SHARE = 'app_shared';
export const ADVICE_SHARED = 'advice_shared';
export const GAME_SHARED = 'game_shared';
export const FAVOURITE_ADVICE_ADDED = 'favourite_advise_added'; // advise_id
export const FAVOURITE_GAME_ADDED = 'favourite_game_added'; //game_id
export const DEVELOPMENT_NOTIFICATION_ON = 'development_notification_on'; //,enabled:true/false
export const DEVELOPMENT_NOTIFICATION_OFF = 'development_notification_off'; //,enabled:true/false
export const GROWTH_NOTIFICATION_ON = 'growth_notification_on'; //,enabled:true/false
export const GROWTH_NOTIFICATION_OFF = 'growth_notification_off'; //,enabled:true/false
export const VACCINE_HEALTHCHECKUP_NOTIFICATION_ON = 'vc_hc_notification_on'; //enabled:true/false
export const VACCINE_HEALTHCHECKUP_NOTIFICATION_OFF = 'vc_hc_notification_off'; //enabled:true/false
export const CHATBOT_CATEGORY_SELECTED = 'chatbot_category_selected'; //chatbot category
export const CHATBOT_SUBCATEGORY_SELECTED = 'chatbot_subcategory_selected'; //chatbot subcategory
export const CHATBOT_FAQ_SELECTED = 'chatbot_faq_selected'; //chatbot faq category
export const EMAIL_SENT = 'email_sent'; //Email Sent
export const DONATE_OPENED = 'donate_opened'; //Donate Event
export const ARTICLE_SEARCHED = 'article_searched'; //Article Searched Event
export const ACTIVITY_SEARCHED = 'activity_searched'; //Activity Searched Event
export const TERMS_ACCEPTED = 'terms_accepted'; //Terms accepted Event
export const ONBOARDING_SKIPPED = 'onboarding_skipped'; //Onboarding Skipped Event
