import 'intl';
export const localization=require('@assets/data/xk/localization').default;
import bebboLogoShape1 from '@assets/svg/xk/bebbo_logo_shape.svg';
export const bebboLogoShape=bebboLogoShape1;
import imgLogoChatbotNew1 from '@assets/svg/xk/img-logo-chatbot-new.svg';
export const imgLogoChatbotNew=imgLogoChatbotNew1;
import menubebboLogo from '@assets/svg/xk/bebbomenulogo.svg';
export const menubebboLogoNew=menubebboLogo;
export const AVAILABLE_LANGUAGES =require('../localization/Available_lang_xk').default;
export const taxonomydata =require('@offlinedata/xk/taxonomies').taxonomydata;
export const ActivitiesData =require('@offlinedata/xk/ActivitiesData').ActivitiesData;
export const articledata = require('@offlinedata/xk/article').articledata;
export const basicPagesData =require('@offlinedata/xk/basicPages').basicPagesData;
export const ChildDevelopmentData= require('@offlinedata/xk/ChildDevelopmentData').ChildDevelopmentData;
export const FaqsData = require('@offlinedata/xk/FaqsData').FaqsData ;
export const healthCheckupsData =require('@offlinedata/xk/healthCheckupsData').healthCheckupsData;
export const dailyHomeNotificationdata =require('@offlinedata/xk/dailyHomeNotification').dailyHomeNotificationdata;
export const MileStonesData =require('@offlinedata/xk/MileStonesData').MileStonesData;
export const standardDevData =require('@offlinedata/xk/standardDevData').standardDevData;
export const SurveyData =require('@offlinedata/xk/SurveyData').SurveyData;
export const vaccineData =require('@offlinedata/xk/vaccineData').vaccineData;
export const VideoArticleData =require('@offlinedata/xk/VideoArticleData').VideoArticleData;
