# This is a basic workflow to help you get started with Actions

name: Continuous Integration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  
  pull_request:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - uses: c-hive/gha-yarn-cache@v1

    - name: Install node modules
      run: |
        yarn install
    - name: Run test
      run: |
        yarn test-ci
          
      # Runs a single command using the runners shell
#      - name: Run a one-line script
 #       run: echo Hello, world!

      # Runs a set of commands using the runners shell
  #    - name: Run a multi-line script
  #      run: |
   #       echo Add other actions to build,
    #      echo test, and deploy your project.
