name: iOS Build using Fastlane
on:
  # create:
  #   tags:
  #     - v*
  push:
    branches: 
      - Development
    
  workflow_dispatch:
    inputs:
      message:
        description: 'Build description'
jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: '21.2.0'
    
      - name: Install node modules
        run: |
          npm install 

      - name: Install Fastlane
        run: gem install fastlane -NV

      - name: Authenticate with Apple Developer Portal
        run: fastlane run produce username:'iosdevs@datamatics.com' app_name:'Bebbo' bundle_identifier:'com.datamatics.bebbo'

      - name: Build iOS app
        run: fastlane run gym
