name: iOS

on: [push, pull_request]

jobs:
 build-ios:
    needs: install-and-test
    runs-on: [self-hosted, macos]
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: Build app
        run: |       
          xcodebuild -workspace ParentBuddyApp.xcworkspace -scheme ParentBuddyApp archive -archivePath ParentBuddyApp.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./ParentBuddyApp.xcarchive -exportPath . -exportOptionsPlist ParentBuddyApp/Info.plist
          mv ParentBuddyApp.ipa ../ParentBuddyApp.ipa
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ParentBuddyApp.ipa
          path: ios/build/
          
